version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0-jessie
        environment: 
          NODE_ENV: test
          PGHOST: 17.0.0.1
          PGUSER: flamingeagle9000
      - image: postgres:11.3-alpine
        environment:
          POSTGRES_DB: airbnb_amenities
          POSTGRES_USER: flamingeagle9000
    steps:
      - checkout
      # - run: npm install
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run seed
      - run: npm test
